name: Test workflow

on:
    pull_request:
        branches:
            - master  # Correct list format

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: node:20
        steps:
            - uses: actions/checkout@v3  # Checkout the repository
            - uses: actions/setup-node@v3  # Set up Node.js
              with:
                  node-version: 20
            - run: npm ci  # Install dependencies
            - run: npm test  # Run tests